pipeline:
  name: Build sample-app
  identifier: Build_karthikrajas0526_cloud_sample_app_1782904677807
  projectIdentifier: sampleapp
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and Push
                  identifier: Build_and_Push
                  spec:
                    connectorRef: artifactorydocker
                    repo: trialitw4yy.jfrog.io/docker-local-docker-local/sample-app
                    tags:
                      - <+pipeline.sequenceId>
                    dockerfile: ./Dockerfile
              - step:
                  type: Run
                  name: Trivy Security Scan
                  identifier: Trivy_Security_Scan
                  spec:
                    shell: Sh
                    command: |
                      curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
                      trivy image --exit-code 0 --severity HIGH,CRITICAL --no-progress \
                        trialitw4yy.jfrog.io/docker-local-docker-local/sample-app:<+pipeline.sequenceId>
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
  properties:
    ci:
      codebase:
        connectorRef: account.Github_OAuth_1782904490317
        repoName: karthikrajas0526-cloud/sample-app
        build: <+input>
